##
## EPITECH PROJECT, 2019
## palindrome
## File description:
## Makefile
##

DEBUG_MODE	=	false

CXX	=	g++

INCLUDE_PATH	=	include

CXXFLAGS	=  -I $(INCLUDE_PATH) -Wall -Wextra -l dl #-Werror

ifeq ($(DEBUG_MODE),true)
	CXXFLAGS += -g -g3
endif

EXEC	=	arcade

SRC	=	$(wildcard src/*.cpp)

OBJ	=	$(SRC:.cpp=.o)

END         =   \033[0m
BOLD        =   \033[1m
GREY        =   \033[30m
RED         =   \033[31m
GREEN       =   \033[32m
BLINK       =   \033[32;5m
YELLOW      =   \033[33m
BLUE        =   \033[34m
PURPLE      =   \033[35m
CYAN        =   \033[36m
WHITE       =   \033[37m

all: $(EXEC)

$(EXEC): $(OBJ)
ifeq ($(DEBUG_MODE), true)
	@echo "$(BOLD)$(RED)\n\n\\t-----DEBUG MODE IS ACTIVATED-----"
endif
	@$(CXX) $(SRC) $(CXXFLAGS) -o $(EXEC)
	mv $(EXEC) ../

clean:
	@echo "$(BOLD)$(GREEN)\t-----WORKSPACE CLEANED-----"

fclean: clean
	@rm -rf ../$(EXEC)
	@echo "$(BOLD)$(GREEN)\t-----WORKSPACE FCLEANED-----"

re: fclean all

.PHONY: clean fclean all re
